name: Deploy React Application

on: 
  push:
    branches:
      - fix-bug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
      
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
    - name: Print current directory content
      run: ls -l
      
    - name: Build Docker Image
      run: |
        docker build \
          --build-arg VITE_REACT_APP_URL=${{ secrets.VITE_REACT_APP_URL }} \
          --build-arg VITE_REACT_APP_ASSETS_URL=${{ secrets.VITE_REACT_APP_ASSETS_URL }} \
          --build-arg VITE_CLERK_PUBLISHABLE_KEY=${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }} \
          --build-arg VITE_GOOGLE_SECRET_KEY=${{ secrets.VITE_GOOGLE_SECRET_KEY }} \
          --build-arg VITE_GOOGLE_ID_KEY=${{ secrets.VITE_GOOGLE_ID_KEY }} \
          --build-arg VITE_EMAILJS_SERVICE_ID=${{ secrets.VITE_EMAILJS_SERVICE_ID }} \
          --build-arg VITE_EMAILJS_TEMPLATE_ID=${{ secrets.VITE_EMAILJS_TEMPLATE_ID }} \
          --build-arg VITE_EMAILJS_PUBLIC_KEY=${{ secrets.VITE_EMAILJS_PUBLIC_KEY }} \
          -t davcode46/wander-whiskers-client .
      env:
        DOCKER_BUILDKIT: 1
      
    - name: Publish Image to Docker Hub
      run: docker push davcode46/wander-whiskers-client:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - name: Pull Image from Docker Hub
      run: sudo docker pull davcode46/wander-whiskers-client:latest

    - name: Remove existing container
      run: sudo docker rm -f wander-whiskers-client-container || true

    - name: Run Docker Container
      run: |
        sudo docker run -d -p 80:80 -p 443:443 --name wander-whiskers-client-container davcode46/wander-whiskers-client:latest
